- hosts: localhost
  vars:
    workspace: /tmp/registry-test
    local: true
  tasks:
    - name: Run setup tasks
      include_tasks: setup.yaml
    - name: Run docker test tasks
      include_tasks: docker.yaml
    - name: Run podman test tasks
      include_tasks: podman.yaml
