# This installs docker and runs a buildset registry
- hosts: all
  roles:
    - build-docker-image

- hosts: all
  vars:
    workspace: /tmp/registry-test
    local: false
  tasks:
    - name: Add project atomic PPA
      apt_repository:
        repo: ppa:projectatomic/ppa
      become: true

    - name: Install packages
      package:
        name:
          - docker-compose
          - openssl
          - skopeo
          - buildah
          - podman
        state: present
      become: true
    - name: Run setup tasks
      include_tasks: setup.yaml
    - name: Run docker test tasks
      include_tasks: docker.yaml
    - name: Run podman test tasks
      include_tasks: podman.yaml

# If buildset_registry is defined, that means a parent job is running it;
# only if it is not defined does it mean that we are running it.  If we
# are running it, pause the job so that child jobs will automatically
# use it.
- hosts: localhost
  tasks:
    - name: Pause the job
      when: buildset_registry is not defined
      zuul_return:
        data:
          zuul:
            pause: true
